name: Deploy with cicd
on:
  push:
    branches: main

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          script: "cd /home/ubuntu/devops && ./deploy.sh"
      
    
